import os
import asyncio
from typing import List, Dict, Any, Optional
from datetime import datetime
from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate
from xhtml2pdf import pisa
from dotenv import load_dotenv

from app.agents.base import BaseAgent
from app.config import settings

load_dotenv()

DATA_DIR = settings.DATA_DIR / "travel_data"
ITINERARY_DIR = DATA_DIR / "itineraries"

os.makedirs(ITINERARY_DIR, exist_ok=True)

# --- PDF Helper (Reused) ---
CSS = """<style>
@page{size:A4;margin:2cm}body{font-family:Helvetica,Arial,sans-serif;font-size:11pt;line-height:1.6;color:#333}
h1{color:#2c3e50;border-bottom:2px solid #1abc9c;padding-bottom:10px}
h2{color:#16a085;margin-top:20px;border-bottom:1px solid #eee}
.day-box{background:#f0fcf9;padding:15px;border-left:5px solid #1abc9c;margin:15px 0;border-radius:4px}
.tip{background:#fff3e0;padding:10px;border-radius:4px;font-style:italic}
.footer{font-size:8pt;color:#7f8c8d;text-align:center;margin-top:30px}
</style>"""

def create_pdf(html: str, filename: str) -> str:
    path = ITINERARY_DIR / f"{filename}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    with open(path, "wb") as f:
        pisa.CreatePDF(CSS + html + f'<div class="footer">Generated by Travel Planner Agent - {datetime.now()}</div>', dest=f)
    print(f"📄 PDF Generated: {path}")
    return str(path)

# --- Travel Models ---
class Activity(BaseModel):
    time: str
    activity: str
    location: str
    cost_estimate: str
    notes: str

class DayPlan(BaseModel):
    day: int
    theme: str
    activities: List[Activity]

class Itinerary(BaseModel):
    destination: str
    duration: str
    total_budget_estimate: str
    daily_plans: List[DayPlan]
    packing_list: List[str]
    local_tips: List[str]

class TravelAgent(BaseAgent):
    name = "travel_plan"
    description = "AI Travel Itinerary Planner"
    icon = "✈️"

    async def execute(self, destination: str, duration: str = "3 days", budget: str = "Medium", interests: str = "Sightseeing", **kwargs) -> Dict[str, Any]:
        prompt = ChatPromptTemplate.from_messages([
            ("system", "You are an expert Travel Planner. Create a detailed itinerary."),
            ("human", "Destination: {destination}\nDuration: {duration}\nBudget: {budget}\nInterests: {interests}")
        ])
        chain = prompt | self.model.with_structured_output(Itinerary)
        itinerary = await self._safe_invoke(chain, {
            "destination": destination, 
            "duration": duration, 
            "budget": budget, 
            "interests": interests
        })

        html = f"""
        <h1>Trip to {itinerary.destination} ({itinerary.duration})</h1>
        <p><strong>Budget:</strong> {itinerary.total_budget_estimate}</p>
        
        <h2>Itinerary</h2>
        {''.join([f'''
        <div class="day-box">
            <h3>Day {d.day}: {d.theme}</h3>
            <ul>
                {''.join([f'<li><strong>{a.time}</strong>: {a.activity} ({a.location}) - {a.cost_estimate}<br><em>{a.notes}</em></li>' for a in d.activities])}
            </ul>
        </div>
        ''' for d in itinerary.daily_plans])}
        
        <h2>Local Tips</h2>
        <ul>{''.join([f'<li class="tip">{t}</li>' for t in itinerary.local_tips])}</ul>
        
        <h2>Packing List</h2>
        <ul>{''.join([f'<li>{i}</li>' for i in itinerary.packing_list])}</ul>
        """
        
        pdf_path = await asyncio.to_thread(create_pdf, html, destination.replace(" ", "_")[:20])
        return {"itinerary": itinerary.model_dump(), "pdf": pdf_path}
